### ISSUE TITLE
Linux client

### ISSUE THREAD

**Issue by lhpitn** [MicrosoftDocs/windowsserverdocs.de-de#10]
Hi, what is about a linux client? maybe you could release some of the source of the android and or osx client than someone will be able to port them for sure and you can build some official client for it. Also modern clients for old systems (osx tiger, os/2, solaris) would be very helpful. Of cause you can use rdesktop but it requires enabling the old protocol at server side and usage of gateways is not supported

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [Remotedesktopclients](https://docs.microsoft.com/de-de/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by srvbpigh** [comment]
Hello, @lhpitn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lhpitn 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/windowsserverdocs/issues/2015
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
