### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by Crasher124** [MicrosoftDocs/windowsserverdocs.de-de#11]
Good

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 397b03ea-324c-1ebd-2c19-94b6eda68dcc
* Version Independent ID: 62c547dc-92e8-00f9-1cb9-02aefa2a42aa
* Content: [rem](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/rem#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/rem.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/administration/windows-commands/rem.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @Crasher124
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Crasher124

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
