### ISSUE TITLE
Cannot sync repository https://packages.microsoft.com/rhel/7/prod/

### ISSUE THREAD

**Issue by mdig** [MicrosoftDocs/windowsserverdocs.de-de#12]
Please fix metadata/faulty checksums for rpms in https://packages.microsoft.com/rhel/7/prod/

Syncing this repo localy hangs in state "processing metadata" (Red Hat Satellite)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1e7ed059-d77f-6ce0-8501-fc3afd1c8048
* Version Independent ID: f2d249ee-50e4-52b4-4187-954a84a48ec1
* Content: [Linux-Softwarerepository für Microsoft-Produkte](https://docs.microsoft.com/de-de/windows-server/administration/linux-package-repository-for-microsoft-software#feedback)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by srvbpigh** [comment]
Hello, @mdig
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hallo, @mdig,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/windowsserverdocs/issues/3780.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
