### ISSUE TITLE
stellen Sie sicher, dass öffentliche vertrauenswürdige Zertifikate sowohl für den RD-Sitzungshostserver...

### ISSUE THREAD

**Issue by fgcgithub** [MicrosoftDocs/windowsserverdocs.de-de#14]
hab's schon gefunden ... netsh
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 71daf1a3-fdf6-de26-836e-badff4b8b869
* Version Independent ID: 4631dad7-30cc-f162-7e4f-4d461981c45a
* Content: [Einrichten des Remotedesktop-Webclients für Ihre Benutzer](https://docs.microsoft.com/de-de/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by srvbpigh** [comment]
Hello, @fgcgithub
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hallo, @fgcgithub ,  

vielen Dank für Ihr Feedback. Es freut uns, dass Sie mir unserer Dokumentation zufrieden sind.  

Sie können gerne weiterhin Feedback abgeben, damit wir die Servicequalität kontinuierlich verbessern können.  

Mit freundlichen Grüßen  

das Microsoft DOCS International Team
