### ISSUE TITLE
examples are inconsistent

### ISSUE THREAD

**Issue by AlexanderStohr** [MicrosoftDocs/windowsserverdocs.de-de#17]
[Hier Feedback eingeben]
on the top its "volume in drive %s: %s"
while on the bottom it is "volume in drive %s: is %s".
you see the added "is" - i have to assume that the second is matching with the real world outputs (but having only a non-englisch Windows version to my hands, so it can be different. BTW: its locale dependent!)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f3adb2eb-3c9c-d811-6979-6c23f6712d67
* Version Independent ID: bbf6f4f2-7238-04d9-488d-d3581f50d2a0
* Content: [label](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/label)
* Content Source: [WindowsServerDocs/administration/windows-commands/label.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/administration/windows-commands/label.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @AlexanderStohr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @AlexanderStohr 

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team
