### ISSUE TITLE
SMBv3 Befehle und ETL-Dateien analysieren

### ISSUE THREAD

**Issue by ATR-Master** [MicrosoftDocs/windowsserverdocs.de-de#18]
Auf der Seite https://docs.microsoft.com/de-de/windows-server/storage/file-server/troubleshoot/troubleshooting-smb steht u.a., das
"Die Befehle SMBv3 und spätere Version können nur von Message Analyzer analysiert werden." und das "ETL-Dateien die durch Netsh erzeugt wurden, nur mithilfe von MMA oder Netmonitor 3.4 analysiert werden können".
Toll und wie soll man das anno 2020 jetzt machen, da der MMA zum Jahresbeginn von der Downloadseite genommen wurde und der MMA von Jahren den Netzwerkmonitor abgelöst hat, weil dieser nicht weiterentwickelt wird (und demnach auch nicht mehr zum Download zur Verfügung steht??)
Wie soll man jetzt die ETL-Dateien analysieren oder die SMBv3 Ergebnisse prüfen???
Solche Abhängigkeiten sollte man aber auf dem Schirm haben, wenn man Werkzeuge, die man für die tägliche Arbeit benötigt, aus dem Verkehr zieht und deren Dateien aus dem Downloadbereich entfernt, oder????

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 643788d4-ceda-1f1d-a36f-916d207068e7
* Version Independent ID: 9ac5db6c-9619-b699-aabf-1c51faa22c2b
* Content: [Erweiterte Problembehandlung für Server Message Block (SMB)](https://docs.microsoft.com/de-de/windows-server/storage/file-server/troubleshoot/troubleshooting-smb)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/troubleshooting-smb.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/storage/file-server/Troubleshoot/troubleshooting-smb.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by srvbpigh** [comment]
Hello, @ATR-Master
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hallo, @ATR-Master,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/windowsserverdocs/issues/4180.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
