### ISSUE TITLE
German Typo

### ISSUE THREAD

**Issue by unamuno** [MicrosoftDocs/windowsserverdocs.de-de#20]
Typo: SIDs können entweder in Form eines numerischen oder eines anzeigen Amens vorliegen.
Correct: SIDs können entweder in Form eines numerischen oder eines anzeigen Namens vorliegen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5906879b-e678-e3da-c404-07a437b42cc2
* Version Independent ID: 0779c597-9e20-38e0-3ae7-40126f5c2bcb
* Content: [icacls](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/icacls#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/icacls.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/administration/windows-commands/icacls.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @unamuno
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @unamuno 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
