### ISSUE TITLE
Comment in Table

### ISSUE THREAD

**Issue by shawnbarton** [MicrosoftDocs/windowsserverdocs.de-de#21]
The "Calculation summary example" table in the section "Virtualization considerations for RAM" (Link: https://docs.microsoft.com/de-de/windows-server/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services#calculation-summary-example) contains the text "sind sicher???"/"are you sure ??".

Such a comment leads the reader to doubt the accuracy of the information they are presented with in the KB article and should be improved.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 14876129-a683-ad93-6043-26fc6afdb456
* Version Independent ID: 041a6bb3-27cc-dd06-fc45-2f34bb466fc8
* Content: [Kapazitätsplanung für Active Directory Domain Services](https://docs.microsoft.com/de-de/windows-server/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services#calculation-summary-example)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/administration/performance-tuning/role/active-directory-server/capacity-planning-for-active-directory-domain-services.md)
* Product: **windows-server**
* Technology: **performance-tuning-guide**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea; kenbrunf**

**Comment by srvbpigh** [comment]
Hello, @shawnbarton
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @shawnbarton

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/4339

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
