### ISSUE TITLE
Wrong German Translation

### ISSUE THREAD

**Issue by Spartaner-dev** [MicrosoftDocs/windowsserverdocs.de-de#4]
The word "Bitsadmin" is changed to "Bigsadmin" from english to german. 
I have tried, the function "Bigsadmin" don't exist. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: af182a65-33f1-7433-ff12-7b1486490d80
* Version Independent ID: b3acc7a9-dbd5-15b0-f77a-4704f2ea06b9
* Content: [biout admin-Beispiele](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/bitsadmin-examples#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/bitsadmin-examples.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/administration/windows-commands/bitsadmin-examples.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @Spartaner-dev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Spartaner-dev 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/bitsadmin-examples#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
