### ISSUE TITLE
Kernel parameter wurde übersetzt (elevator=>Lift)

### ISSUE THREAD

**Issue by DamianFekete** [MicrosoftDocs/windowsserverdocs.de-de#5]
Ein Kernel Parameter (als Parameter in Grub übergeben) wurde von ` elevator = noop ` auf ` Lift = noop ` übersetzt.

Er sollte nicht übersetzen werden.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 17bc364f-8fd0-b273-50bc-63a0d240f8d0
* Version Independent ID: dd4c402b-1f9f-f3d9-bb98-4b9c2c20f04a
* Content: [Bewährte Methoden für die Ausführung von Linux unter Hyper-V](https://docs.microsoft.com/de-de/windows-server/virtualization/hyper-v/Best-Practices-for-running-Linux-on-Hyper-V#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Best-Practices-for-running-Linux-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/virtualization/hyper-v/Best-Practices-for-running-Linux-on-Hyper-V.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @shirgall
* Microsoft Alias: **kathydav**

**Comment by srvbpigh** [comment]
Hello, @DamianFekete
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @DamianFekete 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/windowsserverdocs/issues/3404
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
