### ISSUE TITLE
In Child/Root Domain scenario you get a konflikt with setspn /x /f  CN=krbtgt,CN=Users,DC=xyz,DC=de although probably ok

### ISSUE THREAD

**Issue by mailgut** [MicrosoftDocs/windowsserverdocs.de-de#6]
In Child/Root Domain scenario you get shown a konflikt if you execute setspn /x /f  with this account: CN=krbtgt,CN=Users,DC=xyz,DC=de.

You also get in the eventlog an event with id 11 source "Kerberos-Key-Distribution-Center", saying you have duplicate spns. In the Eventlog event it is not clear what spn is duplicate as it is a long number. 

Can the long number stand for the krbtgt? 

Accourding to findings in the internet in Child/Root Domains the spn for krbtgt is duplicate by design and that is no source for problems.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f678ae81-2f77-e958-d82b-810b24285fba
* Version Independent ID: c924cb81-a2eb-839e-ac09-2333960908cf
* Content: [SPN- und UPN-Eindeutigkeit](https://docs.microsoft.com/de-de/windows-server/identity/ad-ds/manage/component-updates/spn-and-upn-uniqueness#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/component-updates/SPN-and-UPN-uniqueness.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/identity/ad-ds/manage/component-updates/SPN-and-UPN-uniqueness.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @mailgut
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @mailgut

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/3429

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
