### ISSUE TITLE
Restricting Logon to lower tier ressources via GPO

### ISSUE THREAD

**Issue by Bencox89** [MicrosoftDocs/windowsserverdocs.de-de#9]
The GPO to restrict access to lower tier ressourcens "Restrict Administrators from logging onto lower tier hosts" only restricts logon as batch and service for tier0/1 admin accounts, while the GPO to restrict access to Tier 1 Servers also restricts interactive logins. As i understand the documentation tier 0/1 accounts should not be able to log into a standard workstation. Is this by design or  should the restriction to log on to standard workstation be added?

kind regards

[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fd5878a8-a83e-e75d-ddae-59edc04e7138
* Version Independent ID: 0f0cbbe4-20da-3abe-1a7c-effc608d8cca
* Content: [Schützen deiner Organisation mit Arbeitsstationen mit privilegiertem Zugriff](https://docs.microsoft.com/de-de/windows-server/identity/securing-privileged-access/privileged-access-workstations?redirectedfrom=MSDN)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @Bencox89
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Bencox89

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/3622

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
